---
- hosts: localhost
	connection: local
	become: true #enables sudo

	tasks:
		- name: install packages
			package:
				name: 
					- i3
					- xbindkeys
					- polybar
					- rofi
					- nm-applet
					- cbatticon
					- nano
					- curl
					- htop
					- git
					- yay
					- tmux
					- tmuxinator
					- docker
					- kubectl
					- chromium
					- beekeeper-studio
					- alacritty
					- yakuake
					- doctl
					- lens-desktop
					- sublime-text-4
					- code

		- name: Create Projects directory
			file:
				path: ~/Projects
				state: directory

		- name: Clone dotfiles repository
			git:
		    	repo: https://github.com/twoojoo/dotfiles.git
		    	dest: ~/Projects

		- name: Create SmartPricing directory
			file:
				path: ~/SmartPricing
				state: directory

		- name: Create SmartPricing/sources directory
			file:
				path: ~/SmartPricing/sources
				state: directory

		


 