---
- hosts: localhost
	connection: local
	become: true #enables sudo

	tasks:

    - name: update arch
      pacman:
        update_cache: yes
        upgrade: yes

		- name: install packages
			pacman:
				name: 
					- alacritty
					- beekeeper-studio
					- cbatticon
					- chromium
					- code
					- devtools
					- docker
					- doctl
					- curl
					- git
					- htop
					- i3
					- yay
					- yakuake
					- kubectl
					- lens-desktop
					- nano
					- ncdu
					- nm-applet
					- openssh
					- polybar
					- rofi
					- rsync
					- sublime-text-4
					- tmux
					- tmuxinator
					- trash-cli
					- xbindkeys

		- name: enable and start ssh service
      systemd:
        name: sshd
        enabled: yes
        state: started

		- name: Create Projects directory
			file:
				path: ~/Projects
				state: directory

		- name: Clone dotfiles repository
			git:
		    	repo: https://github.com/twoojoo/dotfiles.git
		    	dest: ~/Projects

		- name: Sync dotfiles
			synchronize:
				src: ~/Projects/dotfiles/*
				dest: ~/

		- name: Create SmartPricing/sources directory
			file:
				path: ~/SmartPricing/sources
				state: directory
				recurse: yes

		


 